// src/pages/MealPlanGenerator.js - Modern AI Meal Plan Generator with Enhanced UI

import React, { useState } from 'react';
import {
  Typography,
  Box,
  Grid,
  Chip,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Stack,
  Paper,
} from '@mui/material';
import {
  AutoAwesome,
  RestaurantMenu,
  LocalFireDepartment,
  Save,
  Restaurant,
  Fastfood,
  LocalDining,
  Coffee,
  TrendingUp,
  CameraAlt,
} from '@mui/icons-material';
import { useAuth } from '../contexts/AuthContext';

// Import new design system components
import { PageContainer } from '../components/design-system';
import { Alert } from '../components/design-system';

// Import new hooks
import { useGenerateMealPlan, useSaveMealPlan } from '../hooks/useMeals';

// Import our modern components
import ModernCard, { StatCard } from '../components/ModernCard';
import { PrimaryButton, SecondaryButton } from '../components/ModernButton';
import AIModelBadge from '../components/AIModelBadge';
import MealPhotoRecognition from '../components/MealPhotoRecognition';

const MealPlanGenerator = () => {
  const { user } = useAuth();

  // Use new hooks
  const { execute: generateMealPlan, loading: generating, error: generateError } = useGenerateMealPlan();
  const { execute: saveMealPlan, loading: saving, error: saveError } = useSaveMealPlan();

  // State management
  const [mealPlan, setMealPlan] = useState(null);
  const [success, setSuccess] = useState('');
  const [isPhotoRecognitionOpen, setPhotoRecognitionOpen] = useState(false);

  const error = generateError
    ? (generateError.message || 'An unexpected error occurred.')
    : saveError
    ? (saveError.message || 'Failed to save meal plan.')
    : '';

  // All functions preserved exactly as original
  const handleGeneratePlan = async () => {
    setSuccess('');
    setMealPlan(null);

    try {
      const response = await generateMealPlan({});

      if (!response.ai_generated) {
        throw new Error('AI failed to generate a meal plan. Please try again.');
      }

      setMealPlan(response);
      setSuccess(`Your personalized meal plan has been generated by ${response.ai_model}!`);
    } catch (err) {
      // Error handled by hook
    }
  };

  const handleSavePlan = async () => {
    if (!mealPlan) return;

    try {
      // Prepare meal plan data for saving
      const mealPlanData = {
        name: `Meal Plan - ${new Date().toLocaleDateString()}`,
        target_calories: mealPlan.target_calories,
        target_protein: mealPlan.target_protein,
        target_carbs: mealPlan.target_carbs,
        target_fat: mealPlan.target_fat,
        meals: mealPlan.meals,
        ai_generated: mealPlan.ai_generated,
        ai_model: mealPlan.ai_model,
      };

      await saveMealPlan(mealPlanData);
      setSuccess('Meal plan saved successfully! View it in your meal plan library.');
    } catch (err) {
      console.error('Failed to save meal plan:', err);
      setSuccess(''); // Clear any previous success message
    }
  };

  const handleMealAnalyzed = (analysis) => {
    setSuccess(`✨ Meal analyzed! ${analysis.meal_name} - ${analysis.nutrition?.calories || 0} calories detected.`);
    console.log('Meal analysis:', analysis);
    // You can add logic here to save to meal log if needed
  };

  // Get meal icon based on type
  const getMealIcon = (mealType) => {
    const type = mealType.toLowerCase();
    if (type.includes('breakfast')) return <Coffee />;
    if (type.includes('lunch')) return <LocalDining />;
    if (type.includes('dinner')) return <Restaurant />;
    if (type.includes('snack')) return <Fastfood />;
    return <RestaurantMenu />;
  };

  // Check if profile is complete
  const isProfileIncomplete = !user?.weight || !user?.height || !user?.age || 
                             !user?.gender || !user?.activity_level || !user?.fitness_goal;
  
  let totalProtein = 0;
  let totalCarbs = 0;

  if (mealPlan && mealPlan.meals) {
    Object.values(mealPlan.meals).forEach(meal => {
      if (typeof meal.protein === 'number') totalProtein += meal.protein;
      if (typeof meal.carbs === 'number') totalCarbs += meal.carbs;
      // Add fallback keys if your protein/carbs use a different name:
      if (typeof meal.protein_grams === 'number') totalProtein += meal.protein_grams;
      if (typeof meal.carbs_grams === 'number') totalCarbs += meal.carbs_grams;
    });
  }
  return (
    <PageContainer
      title="AI Meal Plan Generator"
      subtitle="Get personalized nutrition plans powered by AI"
      icon="🥗"
      maxWidth="lg"
    >
      {/* Success/Error Messages */}
      {success && (
        <Alert severity="success" closable onClose={() => setSuccess('')} sx={{ mb: 3 }}>
          {success}
        </Alert>
      )}

      {error && (
        <Alert severity="error" closable onClose={() => {}} sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {/* Profile Completeness Warning */}
      {isProfileIncomplete && (
        <Alert 
          severity="info"
          action={
            <SecondaryButton
              size="small"
              onClick={() => window.location.href = '/profile'}
            >
              Complete Profile
            </SecondaryButton>
          }
          sx={{
            mb: 3,
            background: 'rgba(0, 212, 255, 0.1)',
            border: '1px solid rgba(0, 212, 255, 0.2)',
            '& .MuiAlert-message': { color: '#FFFFFF' },
          }}
        >
          Your profile is incomplete. For the most accurate meal plan, please complete your profile with age, weight, height, gender, activity level, and fitness goal.
        </Alert>
      )}

      {/* Success/Error Messages */}
      {success && (
        <Alert 
          severity="success" 
          onClose={() => setSuccess('')}
          sx={{ 
            mb: 3,
            background: 'rgba(16, 185, 129, 0.1)',
            border: '1px solid rgba(16, 185, 129, 0.2)',
            '& .MuiAlert-message': { color: '#FFFFFF' },
          }}
        >
          {success}
        </Alert>
      )}
      
      {error && (
        <Alert severity="error" closable sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {/* Generate Meal Plan Section */}
      <ModernCard
        title="Ready for Your Personalized Plan?"
        subtitle="Our AI will create a meal plan based on your fitness goals and dietary preferences"
        variant="glass"
        sx={{ mb: 4 }}
      >
        <Box sx={{ textAlign: 'center' }}>
          {/* User Profile Summary */}
          {user && (
            <Box sx={{ mb: 3, p: 2, borderRadius: '12px', background: 'rgba(16, 185, 129, 0.05)' }}>
              <Typography variant="body2" sx={{ color: '#CBD5E1', mb: 1, fontWeight: 600 }}>
                🎯 Based on your profile:
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', justifyContent: 'center' }}>
                {user.fitness_goal && (
                  <Chip 
                    label={`Goal: ${user.fitness_goal.replace('_', ' ')}`} 
                    size="small" 
                    variant="outlined"
                    sx={{ color: '#10B981', borderColor: '#10B981' }}
                  />
                )}
                {user.dietary_restrictions?.length > 0 && (
                  <Chip 
                    label={`Dietary: ${user.dietary_restrictions.join(', ')}`} 
                    size="small" 
                    variant="outlined"
                    sx={{ color: '#7C3AED', borderColor: '#7C3AED' }}
                  />
                )}
                {user.activity_level && (
                  <Chip 
                    label={`Activity: ${user.activity_level.replace('_', ' ')}`} 
                    size="small" 
                    variant="outlined"
                    sx={{ color: '#00D4FF', borderColor: '#00D4FF' }}
                  />
                )}
              </Box>
            </Box>
          )}

          <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} justifyContent="center">
            <PrimaryButton
              onClick={handleGeneratePlan}
              disabled={generating}
              loading={generating}
              size="large"
              startIcon={generating ? undefined : <AutoAwesome />}
              sx={{
                minWidth: '280px',
                height: '60px',
                fontSize: '1.125rem',
                fontWeight: 700,
                background: 'linear-gradient(135deg, #10B981 0%, #34D399 100%)',
              }}
            >
              {generating ? 'Generating Your Plan...' : 'Generate My Meal Plan'}
            </PrimaryButton>

            <SecondaryButton
              onClick={() => setPhotoRecognitionOpen(true)}
              size="large"
              startIcon={<CameraAlt />}
              sx={{
                minWidth: '280px',
                height: '60px',
                fontSize: '1.125rem',
                fontWeight: 700,
              }}
            >
              Analyze Meal Photo
            </SecondaryButton>
          </Stack>

          {generating && (
            <Typography variant="body2" sx={{ color: '#CBD5E1', mt: 2 }}>
              🧠 AI is creating your personalized meal plan...
            </Typography>
          )}
        </Box>
      </ModernCard>

      {/* Generated Meal Plan Results */}
      {mealPlan && (
        <>
          {/* Meal Plan Summary */}
          <ModernCard
            title={mealPlan.name || 'Your Personalized Meal Plan'}
            variant="feature"
            headerAction={
              mealPlan.ai_generated && (
                <AIModelBadge
                  aiModel={mealPlan.ai_model}
                  aiGenerated={mealPlan.ai_generated}
                />
              )
            }
            sx={{ mb: 4 }}
          >
            <Grid container spacing={2} sx={{ mb: 3 }}>
              <Grid item xs={12} sm={6} md={3}>
                <StatCard
                  icon={<LocalFireDepartment />}
                  value={mealPlan.target_calories ? `~${mealPlan.target_calories}` : 'N/A'}
                  label="Target Calories"
                  variant="stat"
                />
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <StatCard
                  icon={<RestaurantMenu />}
                  value={Object.keys(mealPlan.meals || {}).length}
                  label="Meals"
                  variant="stat"
                />
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <StatCard
                  icon={<TrendingUp />}
                  value={
                    (mealPlan.macros && typeof mealPlan.macros.protein === 'number' && mealPlan.macros.protein !== 0)
                      ? `${mealPlan.macros.protein}g`
                      : totalProtein > 0
                        ? `${totalProtein}g`
                        : 'N/A'
                  }
                  label="Protein"
                  variant="stat"
                />
                </Grid>
                <Grid item xs={12} sm={6} md={3}>
                <StatCard
                  icon={<Fastfood />}
                  value={
                    (mealPlan.macros && typeof mealPlan.macros.carbs === 'number' && mealPlan.macros.carbs !== 0)
                      ? `${mealPlan.macros.carbs}g`
                      : totalCarbs > 0
                        ? `${totalCarbs}g`
                        : 'N/A'
                  }
                  label="Carbs"
                  variant="stat"
                />
              </Grid>
            </Grid>
            <Box sx={{ display: 'flex', gap: 2, justifyContent: 'center' }}>
              <SecondaryButton
                onClick={handleSavePlan}
                startIcon={<Save />}
                loading={saving}
                disabled={saving}
              >
                {saving ? 'Saving...' : 'Save Plan'}
              </SecondaryButton>
            </Box>
          </ModernCard>

          {/* Daily Nutrition Summary */}
          {mealPlan.macros && (
            <ModernCard
              title="Daily Nutrition Summary"
              subtitle="Macronutrient breakdown for your meal plan"
              variant="glass"
              sx={{ mb: 4 }}
            >
              <TableContainer 
                component={Paper} 
                sx={{ 
                  background: 'rgba(37, 42, 61, 0.6)',
                  borderRadius: '12px',
                }}
              >
                <Table>
                  <TableHead>
                    <TableRow>
                      <TableCell sx={{ color: '#CBD5E1', fontWeight: 600 }}>Nutrient</TableCell>
                      <TableCell align="right" sx={{ color: '#CBD5E1', fontWeight: 600 }}>Amount</TableCell>
                      <TableCell align="right" sx={{ color: '#CBD5E1', fontWeight: 600 }}>% Daily</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    <TableRow>
                      <TableCell sx={{ color: '#FFFFFF' }}>Protein</TableCell>
                      <TableCell align="right" sx={{ color: '#10B981', fontWeight: 600 }}>
                        {mealPlan.macros.protein}g
                      </TableCell>
                      <TableCell align="right" sx={{ color: '#10B981' }}>
                        {Math.round((mealPlan.macros.protein * 4 / mealPlan.target_calories) * 100)}%
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell sx={{ color: '#FFFFFF' }}>Carbohydrates</TableCell>
                      <TableCell align="right" sx={{ color: '#00D4FF', fontWeight: 600 }}>
                        {mealPlan.macros.carbs}g
                      </TableCell>
                      <TableCell align="right" sx={{ color: '#00D4FF' }}>
                        {Math.round((mealPlan.macros.carbs * 4 / mealPlan.target_calories) * 100)}%
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell sx={{ color: '#FFFFFF' }}>Fat</TableCell>
                      <TableCell align="right" sx={{ color: '#FF3366', fontWeight: 600 }}>
                        {mealPlan.macros.fat}g
                      </TableCell>
                      <TableCell align="right" sx={{ color: '#FF3366' }}>
                        {Math.round((mealPlan.macros.fat * 9 / mealPlan.target_calories) * 100)}%
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </TableContainer>
            </ModernCard>
          )}

          {/* Individual Meals */}
          <Grid container spacing={3}>
            {Object.entries(mealPlan.meals || {}).map(([mealType, mealDetails]) => (
              <Grid item xs={12} md={6} key={mealType}>
                <ModernCard
                  title={`${mealType}: ${mealDetails.name}`}
                  variant="glass"
                  headerAction={getMealIcon(mealType)}
                >
                  <Stack spacing={2}>
                    {/* Ingredients */}
                    <Box>
                      <Typography variant="h6" sx={{ 
                        color: '#CBD5E1', 
                        fontWeight: 600, 
                        mb: 1,
                        fontSize: '0.875rem',
                      }}>
                        🥬 Ingredients:
                      </Typography>
                      <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                        {mealDetails.ingredients?.map((ingredient, i) => (
                          <Chip
                            key={i}
                            label={ingredient}
                            size="small"
                            sx={{
                              background: 'rgba(16, 185, 129, 0.1)',
                              color: '#10B981',
                              fontSize: '0.75rem',
                            }}
                          />
                        ))}
                      </Box>
                    </Box>

                    {/* Instructions */}
                    <Box>
                      <Typography variant="h6" sx={{ 
                        color: '#CBD5E1', 
                        fontWeight: 600, 
                        mb: 1,
                        fontSize: '0.875rem',
                      }}>
                        👨‍🍳 Instructions:
                      </Typography>
                      <Typography variant="body2" sx={{ 
                        color: '#94A3B8', 
                        lineHeight: 1.6,
                        background: 'rgba(0, 212, 255, 0.05)',
                        padding: 2,
                        borderRadius: '8px',
                      }}>
                        {mealDetails.instructions}
                      </Typography>
                    </Box>

                    {/* Nutritional Info (if available) */}
                    {mealDetails.calories && (
                      <Box sx={{ 
                        p: 1.5, 
                        borderRadius: '8px', 
                        background: 'rgba(255, 255, 255, 0.05)',
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                      }}>
                        <Typography variant="caption" sx={{ color: '#94A3B8' }}>
                          Estimated Calories
                        </Typography>
                        <Typography variant="body2" sx={{ 
                          color: '#FF3366',
                          fontWeight: 600,
                        }}>
                          ~{mealDetails.calories} cal
                        </Typography>
                      </Box>
                    )}

                    {/* Macronutrients for individual meal */}
                      {typeof mealDetails.protein !== 'undefined' ||
                      typeof mealDetails.carbs   !== 'undefined' ||
                      typeof mealDetails.fat     !== 'undefined' ? (
                        <Box sx={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: 2,
                          mt: 1,
                          mb: 1,
                          flexWrap: 'wrap'
                        }}>
                          {typeof mealDetails.protein !== 'undefined' && (
                            <Chip
                              label={`Protein: ${mealDetails.protein}g`}
                              size="small"
                              sx={{ background: 'rgba(16, 185, 129, 0.1)', color: '#10B981', fontWeight: 600 }}
                            />
                          )}
                          {typeof mealDetails.carbs !== 'undefined' && (
                            <Chip
                              label={`Carbs: ${mealDetails.carbs}g`}
                              size="small"
                              sx={{ background: 'rgba(0, 212, 255, 0.1)', color: '#00D4FF', fontWeight: 600 }}
                            />
                          )}
                          {typeof mealDetails.fat !== 'undefined' && (
                            <Chip
                              label={`Fat: ${mealDetails.fat}g`}
                              size="small"
                              sx={{ background: 'rgba(255, 51, 102, 0.1)', color: '#FF3366', fontWeight: 600 }}
                            />
                          )}
                          {typeof mealDetails.calories !== 'undefined' && (
                            <Chip
                              label={`Calories: ~${mealDetails.calories}`}
                              size="small"
                              sx={{ background: 'rgba(255, 255, 255, 0.07)', color: '#fff', fontWeight: 600 }}
                            />
                          )}
                        </Box>
                      ) : null}
                  </Stack>
                </ModernCard>
              </Grid>
            ))}
          </Grid>

          {/* Meal Plan Footer */}
          <ModernCard
            variant="default"
            sx={{ mt: 4, textAlign: 'center' }}
          >
            <Typography variant="body1" sx={{ color: '#CBD5E1', mb: 2, lineHeight: 1.6 }}>
              💡 This meal plan is personalized based on your fitness goals and dietary preferences.
            </Typography>
            <Typography variant="body2" sx={{ color: '#94A3B8', lineHeight: 1.6 }}>
              🥗 Remember to drink plenty of water, listen to your body's hunger cues, and adjust portions as needed!
            </Typography>
          </ModernCard>
        </>
      )}

      {/* AI Info Footer */}
      <ModernCard variant="glass" sx={{ mt: 4 }}>
        <Box sx={{ textAlign: 'center' }}>
          <Typography variant="body2" sx={{ color: '#CBD5E1', mb: 1 }}>
            🤖 Powered by advanced AI nutrition models and dietary science
          </Typography>
          <Typography variant="body2" sx={{ color: '#94A3B8' }}>
            🍎 Every meal plan is personalized based on your fitness profile and dietary needs
          </Typography>
        </Box>
      </ModernCard>

      {/* Meal Photo Recognition Modal */}
      <MealPhotoRecognition
        isOpen={isPhotoRecognitionOpen}
        onClose={() => setPhotoRecognitionOpen(false)}
        onMealAnalyzed={handleMealAnalyzed}
      />
    </PageContainer>
  );
};

export default MealPlanGenerator;