// src/components/AIModelBadge.js - Modern AI Model Badge Component with Enhanced Styling

import React from 'react';
import { Chip, Tooltip, Box } from '@mui/material';
import {
  AutoAwesome,
  Computer,
  Psychology,
  Settings,
  SmartToy
} from '@mui/icons-material';

const AIModelBadge = ({ aiModel, aiGenerated, size = 'small' }) => {
  // Non-AI generated fallback (preserved functionality)
  if (!aiGenerated || !aiModel) {
    return (
      <Tooltip title="Generated using rule-based algorithms">
        <Chip
          icon={<Settings />}
          label="Rule-based"
          size={size}
          sx={{
            // Modern minimal styling for non-AI
            background: 'rgba(148, 163, 184, 0.15)', // text.tertiary with opacity
            border: '1px solid rgba(148, 163, 184, 0.3)',
            borderRadius: '12px',
            color: '#94A3B8', // text.tertiary
            fontWeight: 500,
            fontSize: '0.75rem',
            backdropFilter: 'blur(10px)',
            transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
            '& .MuiChip-icon': {
              color: '#94A3B8',
              fontSize: '16px',
            },
            '&:hover': {
              background: 'rgba(148, 163, 184, 0.25)',
              borderColor: 'rgba(148, 163, 184, 0.5)',
              transform: 'translateY(-1px)',
              boxShadow: '0 4px 12px rgba(148, 163, 184, 0.2)',
            }
          }}
        />
      </Tooltip>
    );
  }

  // AI model configuration with modern aesthetics (preserved all logic)
  const getModelConfig = (model) => {
    const modelLower = model.toLowerCase();
    
    if (modelLower.includes('groq') || modelLower.includes('llama3')) {
      return {
        icon: <Psychology />,
        label: 'Groq AI',
        gradient: 'linear-gradient(135deg, #00D4FF 0%, #0099CC 100%)', // Primary gradient
        color: '#00D4FF',
        tooltip: 'Generated by Groq Llama3-8B - Ultra-fast AI inference'
      };
    } else if (modelLower.includes('ollama') || modelLower.includes('llama2')) {
      return {
        icon: <Computer />,
        label: 'Ollama AI',
        gradient: 'linear-gradient(135deg, #FF3366 0%, #CC1A44 100%)', // Secondary gradient
        color: '#FF3366',
        tooltip: 'Generated by local Ollama Llama2 - Privacy-focused AI'
      };
    } else if (modelLower.includes('huggingface') || modelLower.includes('dialogpt')) {
      return {
        icon: <SmartToy />,
        label: 'HuggingFace',
        gradient: 'linear-gradient(135deg, #7C3AED 0%, #6D28D9 100%)', // Purple gradient
        color: '#7C3AED',
        tooltip: 'Generated by HuggingFace AI - Open-source intelligence'
      };
    } else if (modelLower.includes('openai') || modelLower.includes('gpt')) {
      return {
        icon: <AutoAwesome />,
        label: 'OpenAI',
        gradient: 'linear-gradient(135deg, #10B981 0%, #059669 100%)', // Success gradient
        color: '#10B981',
        tooltip: 'Generated by OpenAI GPT - Advanced language model'
      };
    } else {
      return {
        icon: <AutoAwesome />,
        label: 'AI Generated',
        gradient: 'linear-gradient(135deg, #00D4FF 0%, #7C3AED 100%)', // Default primary
        color: '#00D4FF',
        tooltip: `Generated by ${model}`
      };
    }
  };

  const config = getModelConfig(aiModel);

  return (
    <Tooltip 
      title={config.tooltip}
      placement="top"
      arrow
      componentsProps={{
        tooltip: {
          sx: {
            background: 'rgba(26, 31, 46, 0.95)',
            backdropFilter: 'blur(20px)',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            borderRadius: '8px',
            fontSize: '0.75rem',
            fontWeight: 500,
          }
        },
        arrow: {
          sx: {
            color: 'rgba(26, 31, 46, 0.95)',
          }
        }
      }}
    >
      <Box
        sx={{
          display: 'inline-flex',
          position: 'relative',
          cursor: 'pointer'
        }}
      >
        <Chip
          icon={config.icon}
          label={config.label}
          size={size}
          sx={{
            // Modern glassmorphism styling with gradients
            background: config.gradient,
            border: 'none',
            borderRadius: '14px', // More rounded for modern look
            color: '#FFFFFF',
            fontFamily: '"Inter", sans-serif',
            fontWeight: 600,
            fontSize: size === 'small' ? '0.75rem' : '0.875rem',
            height: size === 'small' ? '28px' : '32px',
            padding: size === 'small' ? '0 8px' : '0 12px',
            backdropFilter: 'blur(10px)',
            boxShadow: `0 4px 20px ${config.color}30`, // Color-matched shadow with 30% opacity
            transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
            
            // Icon styling
            '& .MuiChip-icon': {
              color: '#FFFFFF',
              fontSize: size === 'small' ? '16px' : '18px',
              marginLeft: '4px',
            },
            
            // Label styling
            '& .MuiChip-label': {
              paddingLeft: '6px',
              paddingRight: '8px',
              fontWeight: 600,
              letterSpacing: '0.01em',
            },

            // Hover effects with enhanced glow
            '&:hover': {
              transform: 'translateY(-2px) scale(1.02)',
              boxShadow: `0 8px 32px ${config.color}50`, // Enhanced glow on hover
              filter: 'brightness(1.1)',
              
              // Subtle pulse animation
              '&::before': {
                content: '""',
                position: 'absolute',
                inset: 0,
                borderRadius: '14px',
                background: config.gradient,
                opacity: 0.3,
                filter: 'blur(8px)',
                zIndex: -1,
                animation: 'pulse 1.5s ease-in-out infinite',
              }
            },

            // Active/pressed state
            '&:active': {
              transform: 'translateY(-1px) scale(1.01)',
              transition: 'all 0.1s ease',
            },

            // Focus state for accessibility
            '&:focus-visible': {
              outline: `2px solid ${config.color}`,
              outlineOffset: '2px',
            }
          }}
        />
        
        {/* Subtle glow background effect */}
        <Box
          sx={{
            position: 'absolute',
            inset: 0,
            borderRadius: '14px',
            background: config.gradient,
            opacity: 0.1,
            filter: 'blur(12px)',
            zIndex: -2,
            pointerEvents: 'none',
          }}
        />
      </Box>
    </Tooltip>
  );
};

export default AIModelBadge;